# Generated by Django 5.1.7 on 2025-07-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reminder_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='type',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Group', 'Group')], max_length=50),
        ),
    ]
