# Generated by Django 5.1.7 on 2025-07-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_reminder_message_alter_reminder_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='message',
            field=models.CharField(default='Varsayılan mesaj', max_length=255),
        ),
        migrations.AddField(
            model_name='reminder',
            name='repeat',
            field=models.CharField(choices=[('None', 'None'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='status',
            field=models.CharField(default='scheduled', max_length=50),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='type',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Group', 'Group')], max_length=10),
        ),
    ]
