# Generated by Django 5.1.7 on 2025-07-18 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_reminder_message_reminder_repeat_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reminder',
        ),
    ]
