# Generated by Django 5.1.7 on 2025-07-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
