# Generated by Django 5.1.7 on 2025-07-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_reminder_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='message',
        ),
        migrations.AlterField(
            model_name='reminder',
            name='type',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Group', 'Group')], max_length=20),
        ),
    ]
