# Generated by Django 5.1.7 on 2025-07-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_customer_surname_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
